# Generated by Django 3.1.3 on 2020-11-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchresult_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='protein',
            new_name='genome',
        ),
    ]
